README.md
Improve/fix README notes about required Ansible version and release status
=> Improve/fix README notes about required Ansible version and release status

CHANGELOG.rst
Changelog for the initial 5.0.0 release.
=> Release version 5.0.0

README.md
=> Minor readme tweaks/improvements

README.md
Give more precise links for the roles
```paste below
```
=> More precise links

README.md
Tuesday Tasks, adds a blog post link.
```paste below
```
=> Adds Further Reading Section to Ansible Doc Page

.github/workflows/collection-build.yml, .gitignore, requirements.txt
Add a call to galaxy_importer on the generated tarball to validate it before actual upload on ansible platform
```paste below
```
=> Add galaxy importer to the CI jobs

.github/dependabot.yaml, requirements.txt
Add dependabot to update dependencies
```paste below
```
=> Add dependabot configuration file

.github/workflows/ansible-tests.yml, .github/workflows/collection-build.yml
The log of importer was hidden in case of success. It's more explicit to print it in all cases.
=> Print importer log in all cases

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
Prepare 5.2.0 release
```paste below
```
=> Prepare 5.2.0 release

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
=> Prepare 5.3.0 release

.github/workflows/unit-tests.yml, requirements-ansible-lint.txt, requirements.txt, roles/agent/meta/main.yml, roles/agent/tasks/pkg-redhat.yml
Bump galaxy-importer to the latest version (still pinned for now)
Solve current import errors
This PR only mitigate our issue to unblock the ansible collection release further change are needed to solve this issue long term (WIP on other PRs)
=> Bump galaxy-importer and solve current import errors

.github/workflows/scheduled-ansible-pull.yml, README.md, patches/0001-feat-Amazon-Linux-Amazon-Linux-doesn-t-exist-anymore.patch
Rework the ansible collection to fetch by itself the latest changes on the datadog ansible role and notify failure to datadog.
=> Rework of the ansible collection sync with the ansible-datadog

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
This PR prepares the release 5.4.0. It bumps the version to 5.4.0 and edits the changelog
```paste below
```
=> [BARX-405] Prepare release 5.4.0

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
=> prepare 5.5.0 release

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
Prepare release `5.6.0`
```paste below
```
=> Prepare release 5.6.0

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
Prepare release `5.7.0`
```paste below
```
=> Release 5.7.0

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
=> Release collection 5.9.0

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
=> release 5.10.0

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
prepare for release 6.0.0, which corresponds to ansible role 5.1.0
```paste below
```
=> Release 6.0.0

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
update changelog and references for 6.0.1 release
```paste below
```
=> Release 6.0.1

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
update changelogs and defaults for release 6.1.1
```paste below
```
=> Release 6.1.1

CHANGELOG.rst, galaxy.yml, roles/agent/templates/install_info.j2
Release collection 6.3.0, corresponds to ansible-role 5.4.0
```paste below
```
=> Release collection 6.3.0
